"""Put a 'hebsub' entry in Resolve's Workflow > Scripts menu.

The installed file is a launcher, not the panel. It does one thing: start the
panel as a separate process using the interpreter that has faster-whisper,
torch and the CUDA runtime installed.

That indirection is the whole point. Resolve runs menu scripts in its own
embedded Python, which is not guaranteed to have any of the pipeline's
dependencies on its path -- and debugging an import error inside Resolve's
script host is miserable. The launcher needs nothing but the standard library,
so it cannot fail for that reason.

    python -m hebsub.ui.install            install
    python -m hebsub.ui.install --remove   remove
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

__all__ = ["install", "remove", "script_dirs", "main"]

MENU_NAME = "hebsub — Hebrew subtitles.py"

LAUNCHER = '''"""hebsub — opens the Hebrew subtitle panel.

Generated by `python -m hebsub.ui.install`. Edit that, not this.

Runs the panel in {python!r}, which is the interpreter hebsub's dependencies
were installed into. Resolve's embedded Python is not used for anything except
starting this process.
"""

import subprocess
import sys

PYTHON = r"{python}"
REPO_SRC = r"{src}"


def main():
    env = dict(**__import__("os").environ)
    existing = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = REPO_SRC + (";" + existing if existing else "")
    env["PYTHONIOENCODING"] = "utf-8"
    try:
        subprocess.Popen(
            [PYTHON, "-u", "-m", "hebsub.ui.app"],
            cwd=r"{cwd}",
            env=env,
            creationflags=getattr(subprocess, "CREATE_NEW_CONSOLE", 0)
            if sys.platform == "win32" else 0,
        )
        print("hebsub: panel launched")
    except Exception as exc:
        print("hebsub: could not launch the panel:", exc)
        print("hebsub: python was", PYTHON)


main()
'''


def script_dirs() -> list[Path]:
    """Where Resolve looks for menu scripts, most specific first."""
    out: list[Path] = []
    if sys.platform == "win32":
        appdata = os.environ.get("APPDATA")
        if appdata:
            out.append(
                Path(appdata) / "Blackmagic Design" / "DaVinci Resolve"
                / "Support" / "Fusion" / "Scripts" / "Edit"
            )
        out.append(
            Path(r"C:\ProgramData\Blackmagic Design\DaVinci Resolve"
                 r"\Fusion\Scripts\Edit")
        )
    elif sys.platform == "darwin":
        out.append(
            Path.home() / "Library" / "Application Support" / "Blackmagic Design"
            / "DaVinci Resolve" / "Fusion" / "Scripts" / "Edit"
        )
    else:
        out.append(Path.home() / ".local" / "share" / "DaVinciResolve"
                   / "Fusion" / "Scripts" / "Edit")
    return out


def _target() -> Path:
    for directory in script_dirs():
        if directory.is_dir():
            return directory / MENU_NAME
    directory = script_dirs()[0]
    directory.mkdir(parents=True, exist_ok=True)
    return directory / MENU_NAME


def install(python: str | None = None, src: Path | None = None) -> Path:
    python = python or sys.executable
    src = Path(src) if src else Path(__file__).resolve().parents[2]
    repo = src.parent

    target = _target()
    target.write_text(
        LAUNCHER.format(python=python, src=str(src), cwd=str(repo)),
        encoding="utf-8",
    )
    return target


def remove() -> list[Path]:
    gone = []
    for directory in script_dirs():
        candidate = directory / MENU_NAME
        if candidate.exists():
            candidate.unlink()
            gone.append(candidate)
    return gone


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m hebsub.ui.install",
        description="Add or remove the hebsub entry in Resolve's Scripts menu.",
    )
    parser.add_argument("--remove", action="store_true")
    parser.add_argument(
        "--python", default=None,
        help="interpreter to run the panel with (default: this one)",
    )
    args = parser.parse_args(argv)

    if args.remove:
        gone = remove()
        if gone:
            for path in gone:
                print(f"removed {path}")
        else:
            print("nothing installed")
        return 0

    target = install(python=args.python)
    print(f"installed  {target}")
    print(f"python     {args.python or sys.executable}")
    print()
    print("In Resolve:  Workflow > Scripts > hebsub — Hebrew subtitles")
    print("If it is not there yet, restart Resolve once.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
